# frozen_string_literal: true

module Lexicon
  module Database
    class ReadmeUpdater
      START_MARKER = '<!-- AUTOGEN_DATASOURCES_START -->'
      END_MARKER = '<!-- AUTOGEN_DATASOURCES_END -->'
      SCHEMA = 'lexicon'
      CREDITS_TABLE = 'datasource_credits'

      def initialize(readme_path:, database_factory:, db_url:, table_definitions:, datasource_classes:)
        @readme_path = readme_path
        @database_factory = database_factory
        @db_url = db_url
        @table_definitions = table_definitions
        @datasource_classes = datasource_classes
      end

      def update
        unless readme_path.exist?
          puts "[ NOK ] README update skipped: #{readme_path} not found".yellow
          return
        end

        rows = compute_rows
        block = build_block(rows)
        write_block(block)
        puts "[  OK ] README datasource counts updated (#{rows.size} datasources)".green
      end

      private

        attr_reader :readme_path, :database_factory, :db_url, :table_definitions, :datasource_classes

        def compute_rows
          database = database_factory.new_instance(url: db_url)
          sets = table_definitions.reject { |set| set.name == CREDITS_TABLE }

          sets.map do |set|
            total = set.definitions.sum { |table| count_rows(database, table.name) }
            bytes = set.definitions.sum { |table| total_relation_size(database, table.name) }
            klass = datasource_classes[set.name]
            credits = klass&.get_credits&.first

            {
              name: set.name,
              count: total,
              size_mb: bytes.to_f / (1024 * 1024),
              spatial: spatial?(set),
              updated_at: credits&.updated_at,
              provider: credits&.provider,
              description: klass&.description
            }
          end
        end

        def count_rows(database, table_name)
          return 0 unless database.table_exists?(table_name, schema: SCHEMA)

          result = database.query(%(SELECT COUNT(*) AS count FROM "#{SCHEMA}"."#{table_name}"))
          Integer(result.first['count'])
        end

        def total_relation_size(database, table_name)
          return 0 unless database.table_exists?(table_name, schema: SCHEMA)

          result = database.query(%(SELECT pg_total_relation_size('"#{SCHEMA}"."#{table_name}"') AS bytes))
          Integer(result.first['bytes'])
        end

        def spatial?(set)
          set.definitions.any? { |table| table.sql.to_s.include?('postgis.geometry') }
        end

        def build_block(rows)
          body = rows.sort_by { |row| row[:name] }.map do |row|
            [
              "| `#{row[:name]}`",
              format_number(row[:count]),
              format_size_mb(row[:size_mb]),
              row[:spatial] ? '✔' : '⨯',
              cell(row[:updated_at]),
              cell(row[:provider]),
              cell(row[:description]),
              ''
            ].join(' | ')
          end.join("\n")

          [
            START_MARKER,
            '<!-- Auto-generated by `./lexicon dump all`. Do not edit by hand. -->',
            '',
            '### Computed record counts',
            '',
            '| Datasource | Record count | Size (MB) | Spatial | Last updated | Provider | Description |',
            '| --- | ---: | ---: | :---: | :---: | --- | --- |',
            body,
            '',
            "_Last refreshed: #{Time.now.utc.strftime('%Y-%m-%d %H:%M UTC')}_",
            END_MARKER
          ].join("\n")
        end

        def format_size_mb(value)
          return '0' if value.nil? || value <= 0

          if value >= 100
            format_number(value.round)
          elsif value >= 10
            value.round(1).to_s
          else
            value.round(2).to_s
          end
        end

        def cell(value)
          return '' if value.nil?

          value.to_s.gsub('|', '\\|').gsub(/\s+/, ' ').strip
        end

        def format_number(number)
          number.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
        end

        def write_block(block)
          content = File.read(readme_path)

          updated = if content.include?(START_MARKER) && content.include?(END_MARKER)
                      content.sub(
                        /#{Regexp.escape(START_MARKER)}.*?#{Regexp.escape(END_MARKER)}/m,
                        block
                      )
                    else
                      inject_block(content, block)
                    end

          File.write(readme_path, updated)
        end

        def inject_block(content, block)
          anchor = "\nSee [doc/DATASOURCES.md]"

          if content.include?(anchor)
            content.sub(anchor, "\n#{block}\n#{anchor}")
          else
            "#{content}\n\n#{block}\n"
          end
        end
    end
  end
end
