# frozen_string_literal: true

module Lexicon
  module Database
    class ReadmeUpdater
      START_MARKER = '<!-- AUTOGEN_DATASOURCES_START -->'
      END_MARKER = '<!-- AUTOGEN_DATASOURCES_END -->'
      SCHEMA = 'lexicon'
      CREDITS_TABLE = 'datasource_credits'

      def initialize(readme_path:, database_factory:, db_url:, table_definitions:)
        @readme_path = readme_path
        @database_factory = database_factory
        @db_url = db_url
        @table_definitions = table_definitions
      end

      def update
        unless readme_path.exist?
          puts "[ NOK ] README update skipped: #{readme_path} not found".yellow
          return
        end

        counts = compute_counts
        block = build_block(counts)
        write_block(block)
        puts "[  OK ] README datasource counts updated (#{counts.size} datasources)".green
      end

      private

        attr_reader :readme_path, :database_factory, :db_url, :table_definitions

        def compute_counts
          database = database_factory.new_instance(url: db_url)
          sets = table_definitions.reject { |set| set.name == CREDITS_TABLE }

          sets.map do |set|
            total = set.definitions.sum { |table| count_rows(database, table.name) }
            [set.name, total]
          end
        end

        def count_rows(database, table_name)
          return 0 unless database.table_exists?(table_name, schema: SCHEMA)

          result = database.query(%(SELECT COUNT(*) AS count FROM "#{SCHEMA}"."#{table_name}"))
          Integer(result.first['count'])
        end

        def build_block(counts)
          rows = counts.sort_by { |name, _| name }.map do |name, count|
            "| `#{name}` | #{format_number(count)} |"
          end.join("\n")

          [
            START_MARKER,
            '<!-- Auto-generated by `./lexicon dump all`. Do not edit by hand. -->',
            '',
            '### Computed record counts',
            '',
            '| Datasource | Record count |',
            '| --- | ---: |',
            rows,
            '',
            "_Last refreshed: #{Time.now.utc.strftime('%Y-%m-%d %H:%M UTC')}_",
            END_MARKER
          ].join("\n")
        end

        def format_number(number)
          number.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
        end

        def write_block(block)
          content = File.read(readme_path)

          updated = if content.include?(START_MARKER) && content.include?(END_MARKER)
                      content.sub(
                        /#{Regexp.escape(START_MARKER)}.*?#{Regexp.escape(END_MARKER)}/m,
                        block
                      )
                    else
                      inject_block(content, block)
                    end

          File.write(readme_path, updated)
        end

        def inject_block(content, block)
          anchor = "\nSee [doc/DATASOURCES.md]"

          if content.include?(anchor)
            content.sub(anchor, "\n#{block}\n#{anchor}")
          else
            "#{content}\n\n#{block}\n"
          end
        end
    end
  end
end
